FROM golang:1.21.2

RUN update-ca-certificates

RUN addgroup --gid 1000 docker && \
    adduser --uid 1000 --ingroup docker --disabled-password --gecos "" docker

WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o app .

USER docker
CMD [ "go", "test", "-cover", "./..." ]

