version: '3.7'

services:

  cli:
    image: aswa
    build: .
    environment:
      - ASWA_URL
      - ASWA_EXPECTED_STATUS
      - ASWA_TIMEOUT
  test:
    image: aswa_test
    build:
      context: .
      dockerfile: Dockerfile.test
