version: '3.7'

services:

  aswa:
    image: aswa
    build: .
    # volumes:
    #   - ./config:/config
    environment:
      - SLACK_TOKEN=${SLACK_TOKEN}
      - SLACK_CHANNEL_ID=${SLACK_CHANNEL_ID}
      - SLACK_CHANNEL_DEV_ID=${SLACK_CHANNEL_DEV_ID}
      - SLACK_CHANNEL_PROD_ID=${SLACK_CHANNEL_PROD_ID}
      - SLACK_CHANNEL_SAAS_ID=${SLACK_CHANNEL_SAAS_ID}
  test:
    image: aswa_test
    build:
      context: .
      dockerfile: Dockerfile.test
