version: '3.7'

services:

  aswa:
    image: aswa
    build: .
    # volumes:
    #   - ./config:/config
    environment:
      - SLACK_TOKEN=${SLACK_TOKEN}
      - SLACK_CHANNEL_ID=${SLACK_CHANNEL_ID}
      - YAML_PATH=${YAML_PATH}
      - CLUSTER_INFO=${CLUSTER_INFO}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
  test:
    image: aswa_test
    build:
      context: .
      dockerfile: Dockerfile.test
