version: '3.8'

services:

  aswa:
    image: aswa
    build: .
    # volumes:
    #   - ./config:/config
    environment:
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - CLUSTER_INFO=${CLUSTER_INFO}
      - OUTPUT_SLACK=${OUTPUT_SLACK:-false}
      - PROM_AGGREGATION_GATEWAY_URL=${PROM_AGGREGATION_GATEWAY_URL}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - YAML_PATH=${YAML_PATH:-config/dev.applications.yml}

  test:
    image: aswa_test
    build:
      context: .
      dockerfile: Dockerfile.test
