docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:20.10.6-dc-1.29.1-0
  working_directory: ~/app

version: 2.1
jobs:
  build-test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build test
          command: |
            docker-compose build test
      - run:
          name: Check formatting
          command: |
            docker-compose run test gofmt -l .
            test -z $(docker-compose run test gofmt -l .)
            #docker-compose run test golint -set_exit_status
      - run:
          name: Test
          command: |
            docker-compose run test
      - run:
          name: Build app
          command: |
            docker-compose build
      - run:
          name: Push image
          command: |
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            docker tag aswa quay.io/nyulibraries/aswa:${BRANCH_NO_SLASH}
            docker tag aswa quay.io/nyulibraries/aswa:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
            docker login -u "$QUAY_USERNAME" --password "$QUAY_PASSWORD" quay.io
            docker push quay.io/nyulibraries/aswa:${BRANCH_NO_SLASH}
            docker push quay.io/nyulibraries/aswa:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}

workflows:
  version: 2
  build-test:
    jobs:
      - build-test

