applications:
  - name: specialcollections
    url: 'https://specialcollections.library.nyu.edu/search'
    expected_status: 200
  - name: specialcollections-dev
    url: 'https://specialcollections-dev.library.nyu.edu/search'
    expected_status: 200
  - name: library-nyu-edu
    url: 'http://library.nyu.edu'
    expected_status: 301
    expected_redirect_location: 'https://library.nyu.edu'

