applications:
  - name: specialcollections
    url: 'https://specialcollections.library.nyu.edu/search/'
    expected_status: 200
    timeout: 600ms
    expected_location: 'https://specialcollections.library.nyu.edu/search/'
  - name: specialcollections-dev
    url: 'https://specialcollections-dev.library.nyu.edu/search'
    expected_status: 200
  - name: library-nyu-edu
    url: 'http://library.nyu.edu/'
    expected_status: 301
    expected_location: 'https://library.nyu.edu/'

