applications:
  - name: bess
    url: 'https://cdn-dev.library.nyu.edu/bess-vue/app.min.js'
    expected_status: 200
  - name: bobcat-linker
    url: 'https://dev.library.nyu.edu/persistent'
    expected_status: 301
    expected_location: 'https://app.library.nyu.edu/bobcat-linker'
  - name: bobcat-permalink
    url: 'https://bobcatdev.library.nyu.edu/permalink/f/ci13eu/nyu_aleph009700570'
    expected_status: 303
    expected_location: 'https://search.library.nyu.edu/discovery/fulldisplay?docid=alma990097005700107871&context=L&vid=01NYU_INST:NYU'
  - name: campus-media-equipment
    url: 'https://dev.library.nyu.edu/services/campus-media/classrooms/'
    expected_status: 301
    expected_location: 'https://www.appsheet.com/start/014cf30a-fbbc-454b-9fd8-b5bde95eb0d3'
  - name: getit
    url: 'https://getit-dev.library.nyu.edu'
    expected_status: 302
    expected_location: 'https://search.library.nyu.edu/discovery/citationlinker?vid=01NYU_INST:NYU'
  - name: getit-redirect
    url: 'https://getit-dev.library.nyu.edu/resolve?sid=google&auinit=C&aulast=Ottaviani&atitle=Pros+and+cons+of+a+wandering+mind:+a+prospective+study&id=doi:10.3389/fpsyg.2013.00524&title=Frontiers+in+Psychology&volume=4&date=2013&spage=524&issn=1664-1078'
    expected_status: 302
    expected_location: 'https://search.library.nyu.edu/openurl/01NYU_INST/01NYU_INST:NYU?sid=google&auinit=C&aulast=Ottaviani&atitle=Pros+and+cons+of+a+wandering+mind:+a+prospective+study&id=doi:10.3389/fpsyg.2013.00524&title=Frontiers+in+Psychology&volume=4&date=2013&spage=524&issn=1664-1078'
#  - name: getit-ebooks
#    url: 'https://getit-dev.library.nyu.edu/v0/?genre=bookitem&isbn=9780190280390&issn=&title=Our%20Lady%20of%20everyday%20life:%20la%20Virgen%20de%20Guadalupe%20and%20the%20Catholic%20imagination%20of%20Mexican%20women%20in%20America&volume=&issue=&date=20180101&atitle=&aulast=&spage=&sid=EBSCO:Chicano%20Database&pid=XCHD8493320180101Chicano%20Database'
#    expected_status: 200
#    expected_content: 'ebookcentral.proquest.com'
  - name: illiad
    url: 'https://dev.ill.library.nyu.edu'
    expected_status: 200
  - name: libcal-assets
    url: 'https://cdn-dev.library.nyu.edu/libcal/index.min.js'
    expected_status: 200
  - name: libguides-assets
    url: 'https://cdn-dev.library.nyu.edu/libguides/index.min.js'
    expected_status: 200
  - name: library-nyu-edu
    url: 'http://dev.library.nyu.edu'
    expected_status: 301
    expected_location: 'https://dev.library.nyu.edu/'
#  - name: dev-login
#    url: 'https://dev.login.library.nyu.edu'
#    expected_status: 200
  - name: primo-ve
    url: 'https://nyu.primo.exlibrisgroup.com/discovery/search?vid=01NYU_INST:NYU_DEV'
    expected_status: 200
    expected_csp: "object-src blob: 'self' *.exlibrisgroup.com *.exlibrisgroup.com.cn www.google-analytics.com stats.g.doubleclick.net s3.amazonaws.com www.youtube.com youtube.com artic.contentdm.oclc.org search.library.nyu.edu null;worker-src blob: 'self' *.exlibrisgroup.com *.exlibrisgroup.com.cn www.google-analytics.com stats.g.doubleclick.net s3.amazonaws.com www.youtube.com youtube.com artic.contentdm.oclc.org search.library.nyu.edu null;upgrade-insecure-requests; report-uri /infra/CSPReportEndpoint.jsp; report-to csp-report-endpoint;"
  - name: salon
    url: 'https://persistent-dev.library.nyu.edu/arch/does-not-ever-exist'
    expected_status: 400
  - name: specialcollections
    url: 'https://specialcollections-dev.library.nyu.edu/search'
    expected_status: 200
  - name: statuspage-embed
    url: 'https://cdn-dev.library.nyu.edu/statuspage-embed/index.min.js'
    expected_status: 200

