applications:
  - name: primo-ve
    url: 'https://nyu.primo.exlibrisgroup.com/discovery/search?vid=01NYU_INST:NYU'
    expected_status: 200
    expected_csp: "object-src blob: 'self' *.exlibrisgroup.com *.exlibrisgroup.com.cn www.google-analytics.com stats.g.doubleclick.net s3.amazonaws.com www.youtube.com youtube.com artic.contentdm.oclc.org iiif.nlm.nih.gov search.library.nyu.edu; worker-src blob: 'self' *.exlibrisgroup.com *.exlibrisgroup.com.cn www.google-analytics.com stats.g.doubleclick.net s3.amazonaws.com www.youtube.com youtube.com artic.contentdm.oclc.org iiif.nlm.nih.gov search.library.nyu.edu; upgrade-insecure-requests; report-uri /infra/CSPReportEndpoint.jsp; report-to csp-report-endpoint;"
  - name: primo-ve-search
    url: 'https://search.library.nyu.edu/'
    expected_status: 302
    expected_location: 'mng/login'
  - name: primo-ve-search-file
    url: 'https://search.library.nyu.edu/primaws/rest/pub/cslFiles/vid/01NYU_INST:NYU'
    expected_status: 200
    expected_content: 'harvard-kings-college-london'
  - name: primo-ve-search-hamlet
    url: 'https://search.library.nyu.edu/primaws/rest/pub/pnxs?acTriggered=false&blendFacetsSeparately=false&citationTrailFilterByAvailability=true&disableCache=false&getMore=0&inst=01NYU_INST&isCDSearch=false&lang=en&limit=10&newspapersActive=false&newspapersSearch=false&offset=0&otbRanking=false&pcAvailability=false&q=any,contains,hamlet&qExclude=&qInclude=&rapido=false&refEntryActive=true&rtaLinks=true&scope=CI_NYU_CONSORTIA&searchInFulltextUserSelection=false&skipDelivery=Y&sort=rank&tab=Unified_Slot&vid=01NYU_INST:NYU'
    expected_status: 200
    expected_content: 'Hamlet'
  - name: primo-ve-search-html
    url: 'https://search.library.nyu.edu/discovery/search?vid=01NYU_INST:NYU'
    expected_status: 200
    expected_content: 'src="lib/bundle.js?version=9184ada094"'

 
