applications:
  - name: specialcollections
    url: 'https://specialcollections.library.nyu.edu/search/'
    expected_status: 200
  - name: library-nyu-edu
    url: 'http://library.nyu.edu/'
    expected_status: 301
    expected_location: 'https://library.nyu.edu/'
#  - name: guest-passes
#    url: 'https://guestpasses.library.nyu.edu/'
#    expected_status: 401
#    timeout: 1200ms
  - name: primo-explore-views
    url: 'https://bobcat.library.nyu.edu'
    expected_status: 301
    expected_location: 'https://bobcat.library.nyu.edu/primo-explore/search?vid=NYU'
  - name: bobcat-linker
    url: 'https://library.nyu.edu/persistent'
    expected_status: 301
    expected_location: 'https://app.library.nyu.edu/bobcat-linker'
  - name: salon
    url: 'https://persistent.library.nyu.edu'
    expected_status: 301
    expected_location: 'http://persistent.library.nyu.edu/arch'
  - name: pushtocite
    url: 'https://cite.library.nyu.edu/'
    expected_status: 400
  - name: marli
    url: 'https://marli.library.nyu.edu/'
    expected_status: 302
    expected_location: 'https://login.library.nyu.edu/login/passive?client_id=6376ea3aec8082cc1a2f6afa3d97567db266c8287cac4982e7c35765138be3a3&return_uri=https%3A%2F%2Fmarli.library.nyu.edu%2F&login_path=%2Flogin'
  - name: login
    url: 'https://login.library.nyu.edu/'
    expected_status: 200
  - name: eshelf
    url: 'https://eshelf.library.nyu.edu/'
    expected_status: 302
    expected_location: 'https://login.library.nyu.edu/login/passive?client_id=bbcf34b029d1b729dee3db58e6e1b13f469ae756c83d99b345dd1689fd6b36ef&return_uri=https%3A%2F%2Feshelf.library.nyu.edu%2F'
  - name: moloneycollection
    url: 'https://moloney.library.nyu.edu/'
    expected_status: 200
  - name: bravocollection
    url: 'https://web1.library.nyu.edu/bravo_collection/'
    expected_status: 200
  - name: getit
    url: 'https://getit.library.nyu.edu/'
    expected_status: 301
    expected_location: 'http://bobcat.library.nyu.edu/primo-explore/citationlinker?vid=NYU'
  - name: ares-webpages
    url: 'https://ares.library.nyu.edu/'
    expected_status: 200
  - name: web-proxies
    url: 'http://web-pr-proxy1.bobst.nyu.edu/'
    expected_status: 301
    expected_location: 'https://bobcat.library.nyu.edu/'
  - name: campus-media-equipment
    url: 'https://library.nyu.edu/services/campus-media/classrooms/'
    expected_status: 200
  - name: pds-custom
    url: 'https://pds.library.nyu.edu/'
    expected_status: 302
    expected_location: 'http://bobcat.library.nyu.edu'
#  - name: kibana
#    url: 'https://kibana.library.nyu.edu/'
#    expected_status: 401
#  - name: grafana
#    url: 'https://grafana.library.nyu.edu/'
#    expected_status: 302
#    expected_location: '/login'
#  - name: libguides-assets
#    url: 'https://guides.nyu.edu'
#    expected_status: 200
#    timeout: 600ms
  - name: libcal-assets
    url: 'https://nyu.libcal.com'
    expected_status: 200
#  - name: illiad-proxy
#    url: 'https://ill-proxy.library.nyu.edu/'
#    expected_status: 200
#  - name: privileges-guide
#    url: 'https://privileges.library.nyu.edu/'
#    expected_status: 302
#    expected_location: 'https://library.nyu.edu/about/visiting/access-guide/'
#  - name: status-page-embed
#    url: 'https://cdn.library.nyu.edu/statuspage-embed/index.min.js/'
#    expected_status: 403
#  - name: primo-explore-search-embed
#    url: 'https://cdn.library.nyu.edu/bess-vue/app.min.js'
#    expected_status: 403
#  - name: alephJS
#    url: 'https://cdn.library.nyu.edu/aleph/application.min.js'
#    expected_status: 403




