applications:
  - name: alerts
    url: 'https://alerts.library.nyu.edu'
    expected_status: 200
    expected_content: 'About This Site'
  - name: ares-webpages
    url: 'https://ares.library.nyu.edu/'
    expected_status: 200
  - name: circleCI
    url: 'https://status.circleci.com/api/v2/status.json'
    expected_status: 200
    expected_content: 'All Systems Operational'
  - name: lib-guides
    url: 'https://guides.nyu.edu/az/databases'
    expected_status: 200
    expected_content: 'Research Guides'
  - name: libcal
    url: 'https://nyu.libcal.com'
    expected_status: 200
    expected_content: 'Library Classes & Workshops'
  - name: library-answers
    url: 'https://library.answers.nyu.edu'
    expected_status: 200
    expected_content: 'FAQs'
  - name: redHat
    url: 'https://status.redhat.com'
    expected_status: 200
    expected_content: 'All Systems Operational'



